sudo: required

language: php
php:
- '7.1.9'

branches:
  only:
  - master

# travis runtime environment from here or settings. : https://docs.travis-ci.com/user/environment-variables/
env:
  global:
    - ZIP_FILE="php-web-$TRAVIS_BUILD_NUMBER-$TRAVIS_COMMIT.zip"

    # travis-ci secure doc : https://docs.travis-ci.com/user/encryption-keys/
    # before install travis , first install ruby & gem
    # $ gem install travis
    # $ travis encrypt SOMEVAR="secretvalue"

    # AWS_ACCESS_KEY_ID_DEV
    - secure: ""
    # AWS_SECRET_ACCESS_KEY_DEV
    - secure: ""
    # AWS_ACCESS_KEY_ID_STG
    #    - secure: ""
    # AWS_SECRET_ACCESS_KEY_STG
    #    - secure: ""
    # AWS_ACCESS_KEY_ID_PROD , value : AKI....QMQ
    - secure: "hqhCIP/IQbjLv/++fj2Oab0jdwhCzxdC8NxUYZMjGWLFnKBYR2wMLvwYR5C1iWaKH7GQGTmX/qVT/QSVHHphMvwqqdnwWHo5dyhThK8g1nFgPCTg51Jf4v70fXlbJW1DmqYSvMSfpN2leYgwFA/HvDIzs42UbCDdAJoe2pAT/NLrrwLxaJhGrgKjOTv/ID6IWBRQ/Kvui5pY/JhuIqUFKW+WZsFjAMcq7d1hlV7cn+xizYsQ8qJfe9WXTXmOuXbAtj/LrVUtYK1xxfgs2gxphfrqwq26MnAeIBjZZHyRJsVbcqSAht6U/IO6NDEAhhrZxtj2POM7qdTrhg5/z68BfjS5mh91fSQdaCAhXf7U3v8r3/dBz/1gTg7YLMXDFPdHhfpz7kqW5OoEZsq2/wMilWydgo2yoJjCoINBVL4qeC3MsDeRjvg51hTFn78ZVjXHvr92s/h8kFiEM9v1SOj3lR3ILxQMwtH6UCZNL4wC+gdA3dVdOCU86zwMuM2nlZddkRqWfkyacwnak2iOrYg/5voo9MdePMZw4K5H8UA9JPnlKF4gP4llVS8Z+gPAJjC72dBkwyrfl7mk5cyNj6z+dXZXpKzDeUAwXYjETAnWA7FyeTuwnMcjKlhygS7rOm65U+FlRNOrKJXzP3Mnpr2FKX6OKxenTaOt6CdRcNCs3aU="
    # AWS_SECRET_ACCESS_KEY_PROD
    - secure: "Le416pATEarSZhqr0crkIONDCz7JRpIIm4qYXVBSrYUeGVPddsKstrRI5A9T51KRbnyQiD6YFk1lfPCAUZu8W5d5t46msHf9Jwcn+sZ/MngZizkAQ0tlWbBA7jH9AEsKq98p5Cj7bwBj9tvt753ftqUyW12F8fNjtR+WCtn2E3YAsErfiLJs7F7tzZK1niNErzj+fj2mvd755aqN8j6Y6uIMvBYUb6qrXdF0TRBbci2X3wy5Jrb9zV/uejD0mlGjahzzZpIZtEagTAghAA85eC9nUw67VqMV/v+QnWaCRu2qrnwX6bzxXT0Rk82Q9Dw9i54obpp9SwBAAPG69jalj73LsjiiG/jFeLyBM4ZWaHSmGcdP0zPPRVw4hALbIdqFiZ7gKZUNzXYly1ylV51oLVUK6+SDdKh/ezCs46PD+dKW/nT6WxIYOdU2UMvxOHa0lTlF2Yq5fXmtsmjduCmxhXKDGUQb+6QrpmGHkNoQjEA2RW3Jy2UvzAbweg0+shGOoNKgrlnQdUnopqLqwxVRanpb3KEf5WQUQUsxKzb3FzMbxRWVe/wSKu9IxlxhUfX1SPxasAtjODRhWaLqdaaRla2RQ2jqYdLYK5pGDBDUSyy1u5IPUeVFqhMhGGXmL392ghSAHleEvx3167/1H+k837HtsnSmIeoRUgUxYOagYKk="

    # global variables
    - AWS_ACCESS_KEY_ID=''
    - AWS_SECRET_ACCESS_KEY=''
    - AWS_REGION='ap-northeast-1'
    - S3_BUCKET=''
    - S3_FOLDER='demo-lab'
    - CODEDEPLOY_APP_NAME=''
    - CODEDEPLOY_GROUP=''


# notification - https://docs.travis-ci.com/user/notifications
# notifications:
#   email:
#     recipients:
#       - one@example.com
#       - other@example.com
#     on_success: never # default: change
#     on_failure: always # default: always
# integration to slack , setup on slack travis-ci app
notifications:
  email:
    on_failure: always
    on_success: never
  slack:
    rooms:
    - secure: "kXkN3jphexFgHnD71P0yuCCup95ZrzpQlF73FlicSZoJpbCW59bwrWLCMhu3MN6osXEQOl2aeT/LthVwoRwWY2k7EKDkw9sXCVf2PMc+0rWEH4omAORqNKBB1Ja3OugtzXx99LRu5bwYYwNPe4qfq+cp6HAV98yqrz7hK/Nxk+n4KmH2pl1SXVBIFYBKobfoEuwfugK8F5MnMvN7kqzQJC3jqfyVgovJEEcqZ7owUN6CBFEhtzPwosBDNpdCNCGHvhq5H8clRNBtKu5lP/hM2QaD1NLXrZ0vH/pKH5EvxK7xGv/9NRgbNgYednV/pi7Oat9oEVHg1eFqtFpSBXWrvwoyJNNbvQWPSkLNV0ge2VhWspuwUYY8fbKLnpCZevxyEm91jCvNgq8xo2cs8ECIkyEIW5dr+f1fj8VJCQhBOOxfBssgg021zItPmjZo24v7Gmm1+leN5y6z5pvQH2696V6B10ccRSRmX/VouX9unwDQU+IqjtSfLJhIhUnaMIHnIiNLk2Xuk3nfTtyZxvEMkwUnSLpAwlpuE/JO04LUDeBhEhWCOe3Q6Di0sZwo+k+fHDjDsHEKFOFCfejXAFNGcgMgX6zx80hlyPd/cA+ctkoox966noCdfgENzdv91xsrVEldaa7+qieu0kjyvan6nEpTkv86XmDFdeBCkBhRdus="

cache:
  directories:
  - $COMPOSER_CACHE_DIR
  - $HOME/.composer/cache




# build lifecycle - https://docs.travis-ci.com/user/customizing-the-build/
# (OPTIONAL) Install apt addons
# (OPTIONAL) Install cache components
# before_install
# install
# before_script
# script
# (OPTIONAL) before_cache (for cleaning up cache)
# after_success or after_failure
# (OPTIONAL) before_deploy
# (OPTIONAL) deploy
# (OPTIONAL) after_deploy
# after_script

# set -e : when error stop build.
before_install:
  - set -e
  - echo `date +"%Y-%m-%d %H:%M:%S"`
  - echo $TRAVIS_BRANCH
  - if [[ $TRAVIS_BRANCH == "dev" ]]; then
      AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_DEV;
      AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_DEV;
      S3_BUCKET='';
      CODEDEPLOY_APP='';
      CODEDEPLOY_GROUP='';
    fi
  - if [[ $TRAVIS_BRANCH == "staging" ]]; then
      AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_STG;
      AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_STG;
      S3_BUCKET='';
      CODEDEPLOY_APP='';
      CODEDEPLOY_GROUP='';
    fi
  - if [[ $TRAVIS_BRANCH == "master" ]]; then
      AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID_PROD;
      AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY_PROD;
      S3_BUCKET='bucket0117-weiting';
      CODEDEPLOY_APP='stack0117-EC2-CodeDeploy';
      CODEDEPLOY_GROUP='ec2';
    fi


# put testing scripts here
script:
- echo 'script step...'

before_deploy:
- cd "$TRAVIS_BUILD_DIR";
  mkdir "$TRAVIS_BUILD_DIR/zip";
  zip -r "$TRAVIS_BUILD_DIR/zip/$ZIP_FILE" *


deploy:
- provider: S3
  access_key_id: &aws_access_key $AWS_ACCESS_KEY_ID
  secret_access_key: &aws_secret_key
    secure: $AWS_SECRET_ACCESS_KEY
  region: $AWS_REGION
  local_dir: $TRAVIS_BUILD_DIR/zip
  bucket: $S3_BUCKET
  upload-dir: $S3_FOLDER
  skip_cleanup: true
  on:
    all_branches: true

- provider: codedeploy
  access_key_id: *aws_access_key
  secret_access_key: *aws_secret_key
  region: $AWS_REGION
  bucket: $S3_BUCKET
  key: $S3_FOLDER/$ZIP_FILE
  bundle_type: zip
  application: $CODEDEPLOY_APP
  deployment_group: $CODEDEPLOY_GROUP
  wait-until-deployed: true
  on:
    all_branches: true
